# Generated by Django 4.1.7 on 2023-07-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_favoriteitem_user_product_favorite_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='img/blog/instagram/insta-1.jpg', upload_to='img'),
        ),
    ]
