# Generated by Django 4.1.7 on 2023-07-04 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_product_favorite_item_favoriteitem_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteitem',
            name='user',
        ),
    ]
