# Generated by Django 4.1.7 on 2023-07-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_favoriteitem_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='img/avatar.svg', null=True, upload_to=''),
        ),
    ]
